# Generated by Django 5.2.5 on 2025-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama'), ('ROMANCE', 'Romance'), ('COMEDY', 'Comedy'), ('THRILLER', 'Thriller'), ('SCIFI', 'Scifi'), ('DOC', 'Documentary'), ('ANIMATION', 'Animation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
